#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@File    :   qwen_llm.py
@Time    :   2026/03/24
@Author  :   iFlow CLI
@Version :   1.0
@Contact :   
@License :   (C)Copyright 2026
@Desc    :   阿里云千问 Qwen LLM 封装
'''

from typing import Any, Dict, List, Mapping, Optional, Union, Iterator
from langchain.callbacks.manager import CallbackManagerForLLMRun
from langchain.pydantic_v1 import Field
from llm.self_llm import Self_LLM

import openai


class Qwen_LLM(Self_LLM):
    """阿里云千问大模型接口封装
    
    使用OpenAI兼容接口调用千问API
    """

    # 模型名称
    model: str = Field(default="qwen-turbo", alias="model_name")

    # API Key
    qwen_api_key: str = None

    # 最大Token数
    max_tokens: int = 2048

    # Base URL
    base_url: str = "https://dashscope.aliyuncs.com/compatible-mode/v1"

    @property
    def _llm_type(self) -> str:
        """Return type of llm."""
        return "qwen"

    @property
    def _default_params(self) -> Dict[str, Any]:
        """Get the default parameters for calling Qwen API."""
        return {
            "model": self.model,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
        }

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        """Call out to Qwen's create endpoint.

        Args:
            prompt: The prompt to pass into the model.
            stop: Optional list of stop words to use when generating.

        Returns:
            The string generated by the model.

        Example:
            .. code-block:: python

                from llm.qwen_llm import Qwen_LLM

                llm = Qwen_LLM(
                    model="qwen-turbo",
                    temperature=0.7,
                    qwen_api_key="your-api-key"
                )
                response = llm("你好")
        """
        messages = [{"role": "user", "content": prompt}]

        # 设置API密钥和基础URL（使用旧版openai API）
        openai.api_key = self.qwen_api_key
        openai.api_base = self.base_url

        # 调用API
        params = self._default_params
        params.update(kwargs)

        response = openai.ChatCompletion.create(
            messages=messages,
            **params
        )

        # 提取返回内容
        text = response.choices[0].message.content

        # 处理停止词
        if stop is not None:
            text = self._enforce_stop_tokens(text, stop)

        return text

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        """Get the identifying parameters."""
        return {
            "model": self.model,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
            "base_url": self.base_url,
        }